### ISSUE TITLE
Any way to add in the ability to move blocks after they've been placed?

### ISSUE THREAD

**Issue by snowe2010** [skybaks/tm-editor-helpers#1]
Per title, it would be really good to be able to move blocks after they've been placed. Seems like it would probably be pretty difficult, but I haven't dug into how TM/OP plugins are built, so not sure if it's possible.

**Comment by skybaks** [comment]
Do you mean that you would like to nudge a block slightly after placing it in free mode?
There isnt really an existing API in the game for that, but there is a plugin that does something similar https://openplanet.nl/files/109

**Comment by snowe2010** [comment]
Yes, that was what I wanted. Thanks!
