### ISSUE TITLE
Trackmania2 Stadium Support?

### ISSUE THREAD

**Issue by WillWilli** [skybaks/tm-editor-helpers#26]
Is this supposed to work in TM2 Stadium? 
Some of the features work but none of the 'Build' options seem to. I just want to be able to rotate blocks less than 90 degrees at a time. 
If this is possible can you please point me to how to do this? Thanks.

**Comment by skybaks** [comment]
Yeah, not everything is supported in maniaplanet. Specific rotation angles will only work for items and not blocks since free block mode does not exist.

**Comment by WillWilli** [comment]
OK, thanks for the reply mate.
