### ISSUE TITLE
Null Pointer Access

### ISSUE THREAD

**Issue by 1nner-Peace** [skybaks/tm-editor-helpers#51]
First of all, thank you for the update, it is stellar. Presets are going to be a huge time saver, and I appreciate the time you are investing.
That being said, I sadly get some errors:

```
Script exception: Null pointer access
 EditorHelpers.op/:/src/Main.as (line 60, column 9)
  #0 bool Compatibility::IsMapTesting()(EditorHelpers.op/:/src/Main.as line 60)
  #1 void RenderInterface() (EditorHelpers.op/:/src/Main.as line 93)
```
```
Script exception: Null pointer access
 EditorHelpers.op/:/src/EditorFunction/RememberPlacementModes.as (line92, column 13)
  #0 void Compatibility::IsMapTesting()(EditorHelpers.op/:/src/Main.as line 60)
  #1 void Main() (EditorHelpers.op/:/src/Main.as line 187)
```
```
Script exception: Null pointer access
 EditorHelpers.op/:/src/EditorFunction/RememberPlacementModes.as (line92, column 13)
  #0 void EditorHelpers::RememberPlacementModes::Update(float)(EditorHelpers.op/:/src/EditorFunction/RememberPlacementModes.as line 92)
  #1 void Main() (EditorHelpers.op/:/src/Main.as line 187)
```
```
Script exception: Null pointer access
 EditorHelpers.op/:/src/Main.as (line 60, column 9)
  #0 bool Compatibility::IsMapTesting()(EditorHelpers.op/:/src/Main.as line 60)
  #1 void EditorHelpers::Hotkeys::OnKeyPress(bool down, VirtualKey key)(EditorHelper.op/:/src/EditorFunction/Hotkeys.as line 396)
  #2 void OnKeyPress(bool down, VirtualKey key)(EditorHelpers.op/:/src/Main.as line 159)
```
When I get the errors, some parts of the plugin seem to not work any more. If there's other information necessary, I'm happy to send it.

**Comment by skybaks** [comment]
What titlepack are you using when you see these errors? There is an existing issue ( #12 ) that i noticed with non-Nadeo titlepacks that they are missing a large portion of the editor API.

**Comment by 1nner-Peace** [comment]
I don't remember, but I will tell you when it happens again. It most likely was [Shootmania Obstacle](https://prod.live.maniaplanet.com/titles/obstacle@smokegun) though.

**Comment by skybaks** [comment]
I checked obstacle and it looks like that is working for me. Regardless of that, I think I know enough from your original exception messages to put in a fix.
