### ISSUE TITLE
Strange bug when using a texture mod while having the plugin installed

### ISSUE THREAD

**Issue by branko-meow** [skybaks/tm-editor-helpers#73]
Naxanria found the bug, using one of the RPG mods that uses ItemTrackBarrier (the small rectangle barriers) for different textures of rocks (issue not limited to that mod but to those textures at least). In the photo you can see the rocks in upper row are placed with the plugin installed, the bottom row is with the plugin uninstalled. For some reason for some of trackbarrier textures it only leaves the TM logo overlay somehow? and the white one is fully showing original texture instead of modded one.
![image](https://github.com/skybaks/tm-editor-helpers/assets/141512993/cd6c2b97-f188-4e02-9b14-ef2b0deabd4e)

Tried finding if a setting caused it in plugin but we couldn't figure it out, not sure if we tried everything but uninstalling the plugin was only thing we found to fix it. I believe it's a pretty recent bug, likely since the last update of plugin or game?

**Comment by skybaks** [comment]
Could you send me a map that has the items placed in that configuration shown in the screenshot?

**Comment by skybaks** [comment]
And/or could you send me the items + the mod so I can try and replicate the behavior myself?

**Comment by branko-meow** [comment]
Here's a random mod test map i tested it on, you can find the rocks in that configuration on the right, used another rpg mod since i have a locator for it.
https://cdn.discordapp.com/attachments/971934705610027098/1137432065554534492/Mod_testing.Map.Gbx
https://cdn.discordapp.com/attachments/971934705610027098/1137432626530107434/Pic3.2.4.Item.Gbx
https://cdn.discordapp.com/attachments/971934705610027098/1137432854427615332/Pic2.2.4.Item.Gbx
https://cdn.discordapp.com/attachments/971934705610027098/1137432854750572646/Pic1.2.4.Item.Gbx
and the rocks i specifically used, but it happens on all of the rocks.
Also it's weird, in preview before placing it shows up properly, but changes after placing.

**Comment by skybaks** [comment]
Ok I think they may be different because one of them is getting colored White and the other one is Default color.
The last update added persistence to the block/item colors so when you run with the plugin it would start you in the editor with the last color you had when you exited. (See https://github.com/skybaks/tm-editor-helpers/wiki#remember-placement-modes)

You can turn off this behavior in the settings:
![image](https://github.com/skybaks/tm-editor-helpers/assets/52106022/4dd73b22-7bfa-4f2a-bf0e-ca6d49a29af6)

**Comment by skybaks** [comment]
I'm closing this issue since its been a while and I think it was explained by my post above. Open another issue if you still see problems.
