### ISSUE TITLE
game crash when leaving editor too quickly after opening

### ISSUE THREAD

**Issue by ezio416** [skybaks/tm-editor-helpers#76]
When opening maps (especially with a high number of blocks/items) and quickly leaving the editor afterwards, the game will crash with this plugin enabled. This is not exclusive to this plugin, it seems to happen with Editor++ as well, but I've now tested with each being enabled/disabled and both independently cause the crash. I'm thinking there's some reference in the editor being held onto that the game doesn't like.

Issue for Editor++ in case something is found in common between these: https://github.com/XertroV/tm-editor-plus-plus/issues/12

(TM2020)

**Comment by skybaks** [comment]
I might have a theory. Could you enable verbose logging in the editor helper settings and post the output?
Approximately how long a time are you in the editor before exiting? How many custom blocks/items/macroblocks do you have?

**Comment by ezio416** [comment]
With verbose logging (I got nothing without this enabled), I get this before the crash:
```
[   ScriptRuntime] [19:28:59] [EditorHelpers]  EditorHelpers::HasPermission(): OpenSimpleMapEditor:true OpenAdvancedMapEditor:true CreateLocalMap:true
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Event Signals :Update:UpdateSignal_MapFileUpdated: Activate Signal: Signal_MapFileUpdated. Prev flag: 0 New flag: 2834603
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Event Signals :Update:UpdateSignal_BlockItemPlacedRemoved: Activate Signal: Signal_BlockItemPlaced
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Event Signals :Update:UpdateSignal_EnteredEditor: Activate Signal: Signal_EnteredEditor
[   ScriptRuntime] [19:28:59] [EditorRoute]  OnEditorEnter
[   ScriptRuntime] [19:28:59] [MapInfo]  Initialize ML Finder, cotd: false, KO: false, normal: true
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:VerifyInventoryItem: Compared: rootNodeDir.ChildNodes[0].NodeName=Roads  ==  check=Roads
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:VerifyInventoryItem: Compared: rootNodeDir.ChildNodes[0].NodeName=Roads  ==  check=Roads
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:VerifyInventoryItem: Compared: rootNodeDir.ChildNodes[0].NodeName=Official  ==  check=Official
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:VerifyInventoryItem: Compared: rootNodeDir.ChildNodes[0].NodeName=Official  ==  check=Official
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory: Loading inventory blocks
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle: *** YIELDING NOW *** : Time::Now-41786 m_parallelLoadYieldTime-41775
[   ScriptRuntime] [19:28:59] [ghosts-pp]  GhostFinder init
[   ScriptRuntime] [19:28:59] [ghosts-pp]  Scrubber: ResetAll
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle: *** YIELDING NOW *** : Time::Now-41818 m_parallelLoadYieldTime-41807
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle: *** YIELDING NOW *** : Time::Now-41847 m_parallelLoadYieldTime-41836
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle: *** YIELDING NOW *** : Time::Now-41877 m_parallelLoadYieldTime-41866
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle: *** YIELDING NOW *** : Time::Now-41906 m_parallelLoadYieldTime-41895
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory: Loading inventory items
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle: *** YIELDING NOW *** : Time::Now-41933 m_parallelLoadYieldTime-41922
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Editor Inventory :IndexInventory:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle:RecursiveAddInventoryArticle: *** YIELDING NOW *** : Time::Now-41960 m_parallelLoadYieldTime-41949
[   ScriptRuntime] [19:28:59] [EditorHelpers]  Hotkeys :OnKeyPress: Add "Escape" to m_keysDown
```
I'm in the editor for just a couple seconds. This usually happens when I realize I clicked on the wrong map to edit and want to back out right away.

I have about 18,000 custom blocks/items in my Items folder, and renaming that folder does seem to help but doesn't prevent the crash entirely. When it doesn't crash, I'm getting this error every so often:
![Screenshot 2024-03-20 194114](https://github.com/skybaks/tm-editor-helpers/assets/37951898/3ab65241-cd7a-4af5-a7db-5842bbe0f1c3)

Also maybe it doesn't really depend on how many things are in the map. About the same thing happens on a map with a few blocks and one with about 70,000

**Comment by skybaks** [comment]
Yeah, I think I can fix this. Thanks for reporting the issue

**Comment by skybaks** [comment]
[EditorHelpers.zip](https://github.com/skybaks/tm-editor-helpers/files/14681022/EditorHelpers.zip)
Could you try with the attached zip (rename to op) or checkout my branch in #77 ? I believe this should resolve your crash

**Comment by ezio416** [comment]
Sadly I'm still crashing with this version, even on a new map, so it has to be something else with the custom items

**Comment by skybaks** [comment]
I wasnt able to reproduce your game crash. Could you post a log from that? (With verbose enabled)

**Comment by ezio416** [comment]
Sorry I'm just looking at this again. I tried with the latest version and no other plugins installed and it is still consistently crashing.
[Openplanet.log](https://github.com/skybaks/tm-editor-helpers/files/15099515/Openplanet.log)

**Comment by skybaks** [comment]
Dang that's a bummer! Thanks for the log. Just to be clear this is the game crashing and not a plugin exception?

**Comment by ezio416** [comment]
Yes, full game crash unfortunately. It's not the biggest deal in the world if you can't find the exact cause, I've just gotten used to waiting a bit to exit the editor. It would of course be nice if you or someone else was able to reproduce it, but I understand as I'm in the same spot with one of my own plugins crashing people's games that I can't reproduce myself.

**Comment by skybaks** [comment]
I downloaded 30,000 more items and now i can get the crash. Should hopefully have it figured out soon

**Comment by skybaks** [comment]
[EditorHelpers.zip](https://github.com/skybaks/tm-editor-helpers/files/15132490/EditorHelpers.zip)
You can test if you like but I'm almost certain I fixed your crash this time

**Comment by ezio416** [comment]
From what I can tell, this works! Thank you so much!!

**Comment by skybaks** [comment]
Thats great to hear! Thank you for your help and patience in getting to the bottom of this.
