### ISSUE TITLE
Pivot always resets

### ISSUE THREAD

**Issue by 1nner-Peace** [skybaks/tm-editor-helpers#8]
First of all, thank you for your work! This plugin is very useful, I do have an issue with it though. Every time I select a new item, the pivot position resets, which is quite cumbersome. Often times, items are in packs and share similar placement parameters, which is why saving them is helpful. Best regards!

**Comment by skybaks** [comment]
I pushed some updates which should produce the behavior you suggested. If you have a chance I would love to hear if it works the way you wanted. Otherwise I'll probably give it a week or so and then submit this new version for publication

**Comment by 1nner-Peace** [comment]
Wow, that was fast! It's perfect, thank you!

**Comment by skybaks** [comment]
If you have club access you can download a zip of this repo then rename the file extension from .zip to .op or you could clone the repo into your Plugins folder.
